### ISSUE TITLE
Does a resuse model need extra timing guards

### ISSUE THREAD

**Issue by jefft0** [IIIM-IS/AERA#239]
The hand-grab-sphere example has reuse model. The imdl in the LHS has [extra variables](https://github.com/IIIM-IS/AERA/blob/dev/AERA/replicode_v1.2/hand-grab-sphere.replicode#L161-L162) `T0_M0` and `T1_M0` which currently have their own backward guards. But the values are the same as template variables `T0` and `T1`. We should investigate why we can't just use these and omit the extra backward guards. Can we update the code to allow this? (If so, then maybe we don't need pull request #238 .)

**Comment by jefft0** [comment]
ANSWER: With the update in pull request #240, the extra variables `T0_M0` and `T1_M0` are not needed. See the pull request for details.

**Comment by thorisson** [comment]
Hmmm .... are we sure that bwd and fwd chaining *cannot and will ever* be asymmetric wrt time? If the answer is 'yes' this change is justified; if not, it isn't - or at the cery least is premature until we have a wider range of examples to judge from.=KOn 9 Dec 2022, at 15:11, Jeff Thompson ***@***.***> wrote:﻿
The hand-grab-sphere example has reuse model. The imdl in the LHS has extra variables T0_M0 and T1_M0 which currently have their own backward guards. But the values are the same as template variables T0 and T1. We should investigate why we can't just use these and omit the extra backward guards.

**Comment by jefft0** [comment]
There are two sources of asymmetry, both of which are supported. The first is that the time interval of a goal used in backward chaining can be more general than the time interval of the prediction that comes in forward chaining from specific evidence. As explained in pull request #240, the purpose of `match_timings` is to return a positive match if the time intervals intersect, and to proceed in forward chaining with the more specific time interval which matches the general goal time interval.

The second asymmetry comes from the patterns which are matched during the original CTPX process to create models. The model is learned from a specific imdl for the LHS combined with a specific fact for the changed state variable which changed. Usually the timings of these two pieces of evidence are the same, which is why the model builder can re-use the same timing variables. But if the timings are different, then the model builder will use different variables.
