### ISSUE TITLE
WriteFile(...) in init.cpp blocks sometimes

### ISSUE THREAD

**Issue by Leo-Nogismus** [IIIM-IS/AERA#289]
The 'WriteFile(...)' function in the 'PipeOStream& PipeOStream::operator <<(const char *s)' operator sometimes blocks when given a const char array. See:
https://github.com/IIIM-IS/AERA/blob/5b241e69e946043476645e4b1dfc64395ad3fc4a/r_exec/init.cpp#L325-L336

This has happened (so far) when called from here:
https://github.com/IIIM-IS/AERA/blob/5b241e69e946043476645e4b1dfc64395ad3fc4a/r_exec/init.cpp#L186-L187

I suggest removing the '.c_str()' at the end of lines 186 and 187. This way, the 'PipeOStream &PipeOStream::operator <<(std::string &s)' operator is called, which does not seem to have these issues. See:
https://github.com/IIIM-IS/AERA/blob/5b241e69e946043476645e4b1dfc64395ad3fc4a/r_exec/init.cpp#L312-L323

**Comment by jefft0** [comment]
Resolved by PR #290.
